name: Generate and Deploy Coverage Report

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Foundry
      #   uses: foundry-rs/foundry-toolchain@v1
      #   with:
      #     version: nightly

      # - name: Install lcov
      #   run: sudo apt-get install lcov

      # - name: Install genhtml
      #   run: sudo apt-get install lcov

      # - name: Generate and filter LCOV report
      #   run: |
      #     forge coverage --report lcov
      #     lcov --remove lcov.info 'script/*' 'src/test/*' 'src/contracts/math/*' -o pike-coverage.info
      #     genhtml pike-coverage.info --output-directory coverage

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
